Repository gdscvimeet/gdscweb, pull requests merged in 2022-10, with the labels that each got.

#8 Create form.html
  form.html
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#5 Update index.html
  index.html
Labels: good first issue, HACKTOBERFEST-ACCEPTED

#9 Create hacktober.html
  hacktober.html
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#7 Created Index.js File
  DarkMode/index.js
Labels: documentation, enhancement, HACKTOBERFEST-ACCEPTED

#12 frontend for about section
  New Text Document.txt
  about.html
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#13 Create index.html
  login form/index.html
Labels: documentation, HACKTOBERFEST-ACCEPTED

#10 Dark mode button created
  darkmode.html
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#16 Added a Loading animation
  Loading Animation/index.html
  Loading Animation/style.css
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#15 Styling the gdsc website
  about.css
  about.html
  darkmode.css
  darkmode.html
  form.css
  form.html
  index.html
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#22 Images Scroll Issue #21
  Image Scroll/index.html
  Image Scroll/index.js
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#23 Added the css file
  Image Scroll/style.css
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#24 Updated Branch
  Image Scroll/index.html
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#25 Added Loading Animation as Requested by the Lead
  Canvas Loading Animation/index.html
  Canvas Loading Animation/main.js
  Canvas Loading Animation/style.css
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#26 Update main.js
  Canvas Loading Animation/main.js
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#27 Create index.html
  DarkMode/index.html
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#28 Create style.css
  DarkMode/index.js
  DarkMode/style.css
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#29 added the demo images
  DarkMode/dark.jpeg
  DarkMode/white.jpeg
Labels: enhancement, HACKTOBERFEST-ACCEPTED
